[global]
workgroup = WORKGROUP
server string = Samba Server
server role = standalone server
guest account = guest
map to guest = Bad User
server min protocol = SMB2_02
vfs objects = catia fruit streams_xattr
fruit:metadata = stream
fruit:nfs_aces = no
fruit:copyfile = yes
fruit:encoding = native
mangled names = no
dos charset = CP850
# performance tweaks
socket options = IPTOS_LOWDELAY TCP_NODELAY
use sendfile = yes
getwd cache = true
server multi channel support = yes
# hack
#deadtime = 2880

[homes]
#TODO fix
browseable = no
path = /tank/home/%S
writeable = yes
guest ok = no
valid users = %S
create mask = 0700
directory mask = 0600

[TimeMachine]
browseable = no
path = /tank/timemachine
fruit:time machine = yes

[Shared]
browseable = yes
path = /tank/shared
public = yes
writeable = yes
printable = no
veto files = /._*/.DS_Store/
delete veto files = yes
force create mode = 0660
force directory mode = 0770

[Downloads]
browseable = yes
path = /tank/downloads
public = yes
writeable = yes
printable = no
veto files = /._*/.DS_Store/
delete veto files = yes
force create mode = 0660
force directory mode = 0770

[Review]
browseable = yes
path = /tank/review
public = yes
writeable = yes
printable = no
veto files = /._*/.DS_Store/
delete veto files = yes
force create mode = 0660
force directory mode = 0770

