app      := "caddy"
image    := "docker.io/library/caddy:latest"
hostname := app

zfsdir             := "/tank"
persistence        := if path_exists(zfsdir) == "true" { "zfs" } else { "volume" }
zfspool            := "tank"
zfsdataset-app     := zfspool / app
zfsdataset-shared  := zfspool / "shared"

config  := if persistence == "zfs" { zfsdir / app      } else { app + "-config" }
docroot := if persistence == "zfs" { zfsdir / "shared" } else { "shared" }

[private]
default:
    @just --list

all: build setup run

build:
    podman pull {{image}}

setup: mkpersistence

mkpersistence:
    @just mk{{persistence}}

mkzfs:
    zfs create {{zfsdataset-app}}
    mkdir -p {{config}}
    cp Caddyfile {{config}}/
    zfs list {{zfsdataset-shared}} > /dev/null || zfs create {{zfsdataset-shared}}

mkvolume:
    podman volume create {{config}}
    podman cp Caddyfile {{config}}:/
    podman volume create --ignore {{docroot}}

start: run

run:
    podman run --detach --restart unless-stopped \
        --name {{app}} --hostname {{hostname}} --cap-add NET_ADMIN \
        --publish 80:80 \
        --publish 443:443 \
        --publish 443:443/udp \
        --volume {{config}}:/etc/caddy \
        --volume {{docroot}}:/usr/share/{{app}} \
        {{image}}

destroy: stop rmimage rmpersistence

stop:
    podman stop {{app}}
    podman rm {{app}}

rmimage:
    podman rmi {{image}}

rmpersistence:
    @just rm{{persistence}}

rmzfs:
    zfs destroy {{zfsdataset-app}}
    #false && zfs list {{zfsdataset-shared}} > /dev/null && zfs destroy {{zfsdataset-shared}}

rmvolume:
    podman volume rm {{config}}
    #false && podman volume rm --ignore {{docroot}}
